name: test workflow

on: 
  workflow_dispatch:
    inputs:
      name:
        description: "This will ask for your name"
        default: "name"
        type: choice
        options:
          - loveth
          - zola
          - joe
          - val
      
      env:
        description: "what env to use"
        default: "env"
        type: choice
        options:
          - prd
          - dev
          - stg

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout phase
              uses: actions/checkout@v3
            - run: |
                  mkdir test
                  ls .
            - run: |
                  touch play.txt
                  echo 'hello my name is ${{ inputs.name }}, the env i want to use is ${{ inputs.env }}' > play.txt
                  ls .
                  cat play.txt
                  mkdir ~/.ssh/
                  touch ~/.ssh/authorize_keys
                  cp {{ secrets.PUB_KEY }} ~/.ssh/authorize_keys
                  cat ~/.ssh/authorize_keys