name: test workflow

on: 
  workflow_dispatch:
    inputs:
      name:
        description: "This will ask for your name"
        type: choice
        options:
          - loveth
          - zola
          - joe
          - val
      
      env:
        description: "what env to use"
        type: choice
        options:
          - prd
          - dev
          - stg

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout phase
              uses: actions/checkout@v3
            - run: |
                  mkdir test
                  ls .
            - run: |
                  touch play.txt
                  echo 'hello my name is github actions' > play.txt
                  ls .
                  cat play.txt